# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/aman/Desktop/AutomScra/AutomScra.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.urlsTW = QtWidgets.QTableWidget(self.centralwidget)
        self.urlsTW.setGeometry(QtCore.QRect(0, 124, 200, 422))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlsTW.sizePolicy().hasHeightForWidth())
        self.urlsTW.setSizePolicy(sizePolicy)
        self.urlsTW.setMinimumSize(QtCore.QSize(0, 0))
        self.urlsTW.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.urlsTW.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.urlsTW.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.urlsTW.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.urlsTW.setAlternatingRowColors(True)
        self.urlsTW.setShowGrid(True)
        self.urlsTW.setGridStyle(QtCore.Qt.SolidLine)
        self.urlsTW.setRowCount(0)
        self.urlsTW.setColumnCount(1)
        self.urlsTW.setObjectName("urlsTW")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.urlsTW.setHorizontalHeaderItem(0, item)
        self.urlsTW.horizontalHeader().setDefaultSectionSize(200)
        self.urlsTW.horizontalHeader().setMinimumSectionSize(200)
        self.urlsTW.verticalHeader().setDefaultSectionSize(25)
        self.urlsTW.verticalHeader().setSortIndicatorShown(False)
        self.addUrlPB = QtWidgets.QPushButton(self.centralwidget)
        self.addUrlPB.setGeometry(QtCore.QRect(1, 549, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addUrlPB.setFont(font)
        self.addUrlPB.setObjectName("addUrlPB")
        self.removeUrlPB = QtWidgets.QPushButton(self.centralwidget)
        self.removeUrlPB.setGeometry(QtCore.QRect(30, 549, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.removeUrlPB.setFont(font)
        self.removeUrlPB.setObjectName("removeUrlPB")
        self.action_nodePB = QtWidgets.QPushButton(self.centralwidget)
        self.action_nodePB.setGeometry(QtCore.QRect(0, 2, 200, 30))
        self.action_nodePB.setAutoFillBackground(False)
        self.action_nodePB.setObjectName("action_nodePB")
        self.input_nodePB = QtWidgets.QPushButton(self.centralwidget)
        self.input_nodePB.setGeometry(QtCore.QRect(0, 32, 200, 30))
        self.input_nodePB.setObjectName("input_nodePB")
        self.data_nodePB = QtWidgets.QPushButton(self.centralwidget)
        self.data_nodePB.setGeometry(QtCore.QRect(0, 62, 200, 30))
        self.data_nodePB.setObjectName("data_nodePB")
        self.connectorPB = QtWidgets.QPushButton(self.centralwidget)
        self.connectorPB.setGeometry(QtCore.QRect(0, 92, 200, 30))
        self.connectorPB.setObjectName("connectorPB")
        self.executePB = QtWidgets.QPushButton(self.centralwidget)
        self.executePB.setGeometry(QtCore.QRect(59, 549, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.executePB.setFont(font)
        self.executePB.setObjectName("executePB")
        self.treeSA = QtWidgets.QScrollArea(self.centralwidget)
        self.treeSA.setGeometry(QtCore.QRect(203, 3, 595, 571))
        self.treeSA.setWidgetResizable(True)
        self.treeSA.setObjectName("treeSA")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 593, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.treeSA.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuExceute = QtWidgets.QMenu(self.menuEdit)
        self.menuExceute.setObjectName("menuExceute")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUrls = QtWidgets.QAction(MainWindow)
        self.actionUrls.setObjectName("actionUrls")
        self.actionsaveExcel = QtWidgets.QAction(MainWindow)
        self.actionsaveExcel.setObjectName("actionsaveExcel")
        self.actionsaveDB = QtWidgets.QAction(MainWindow)
        self.actionsaveDB.setObjectName("actionsaveDB")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuExceute.addAction(self.actionsaveExcel)
        self.menuExceute.addAction(self.actionsaveDB)
        self.menuEdit.addAction(self.actionUrls)
        self.menuEdit.addAction(self.menuExceute.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutomScra"))
        self.urlsTW.setSortingEnabled(True)
        item = self.urlsTW.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Urls"))
        self.addUrlPB.setText(_translate("MainWindow", "+"))
        self.removeUrlPB.setText(_translate("MainWindow", "-"))
        self.action_nodePB.setText(_translate("MainWindow", "Action Node"))
        self.input_nodePB.setText(_translate("MainWindow", "Input Node"))
        self.data_nodePB.setText(_translate("MainWindow", "Data Node"))
        self.connectorPB.setText(_translate("MainWindow", "Connector"))
        self.executePB.setText(_translate("MainWindow", "Execute"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuExceute.setTitle(_translate("MainWindow", "Exceute options"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionUrls.setText(_translate("MainWindow", "Manage Urls"))
        self.actionsaveExcel.setText(_translate("MainWindow", "Save into Excel"))
        self.actionsaveDB.setText(_translate("MainWindow", "Save into DataBase"))
