# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\singh\git\Auto-w-Scrape\resource\Raw UI file\dataNode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 130)
        Dialog.setMinimumSize(QtCore.QSize(350, 130))
        Dialog.setMaximumSize(QtCore.QSize(350, 130))
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(5, 5, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(5, 35, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(5, 65, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.levelCB = QtWidgets.QComboBox(Dialog)
        self.levelCB.setGeometry(QtCore.QRect(85, 5, 260, 30))
        self.levelCB.setObjectName("levelCB")
        self.typeCB = QtWidgets.QComboBox(Dialog)
        self.typeCB.setGeometry(QtCore.QRect(85, 35, 260, 30))
        self.typeCB.setObjectName("typeCB")
        self.typeCB.addItem("")
        self.typeCB.addItem("")
        self.typeCB.addItem("")
        self.valueLE = QtWidgets.QLineEdit(Dialog)
        self.valueLE.setGeometry(QtCore.QRect(85, 65, 260, 30))
        self.valueLE.setObjectName("valueLE")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(179, 100, 166, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data Node"))
        self.label_1.setText(_translate("Dialog", "Level:"))
        self.label_2.setText(_translate("Dialog", "Type"))
        self.label_3.setText(_translate("Dialog", "Tag:"))
        self.typeCB.setItemText(0, _translate("Dialog", "Text"))
        self.typeCB.setItemText(1, _translate("Dialog", "Media"))
        self.typeCB.setItemText(2, _translate("Dialog", "Table"))
