# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/aman/Desktop/AutomScra/Interface/saveDB.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 220)
        Dialog.setMinimumSize(QtCore.QSize(350, 190))
        Dialog.setMaximumSize(QtCore.QSize(350, 250))
        self.dialectCB = QtWidgets.QComboBox(Dialog)
        self.dialectCB.setGeometry(QtCore.QRect(110, 5, 235, 30))
        self.dialectCB.setObjectName("dialectCB")
        self.dialectCB.addItem("")
        self.dialectCB.addItem("")
        self.dialectCB.addItem("")
        self.dialectCB.addItem("")
        self.dialectCB.addItem("")
        self.hostportLE = QtWidgets.QLineEdit(Dialog)
        self.hostportLE.setGeometry(QtCore.QRect(110, 95, 235, 30))
        self.hostportLE.setObjectName("hostportLE")
        self.userLE = QtWidgets.QLineEdit(Dialog)
        self.userLE.setGeometry(QtCore.QRect(110, 35, 235, 30))
        self.userLE.setObjectName("userLE")
        self.dbLE = QtWidgets.QLineEdit(Dialog)
        self.dbLE.setGeometry(QtCore.QRect(110, 125, 235, 30))
        self.dbLE.setObjectName("dbLE")
        self.passwordLE = QtWidgets.QLineEdit(Dialog)
        self.passwordLE.setGeometry(QtCore.QRect(110, 65, 235, 30))
        self.passwordLE.setObjectName("passwordLE")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(5, 5, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(5, 35, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(5, 65, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(5, 95, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(5, 125, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(179, 190, 166, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(5, 155, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tableLE = QtWidgets.QLineEdit(Dialog)
        self.tableLE.setGeometry(QtCore.QRect(110, 155, 235, 30))
        self.tableLE.setObjectName("tableLE")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Save to DataBase"))
        self.dialectCB.setItemText(0, _translate("Dialog", "PostgreSQL"))
        self.dialectCB.setItemText(1, _translate("Dialog", "MySQL"))
        self.dialectCB.setItemText(2, _translate("Dialog", "Oracle"))
        self.dialectCB.setItemText(3, _translate("Dialog", "Microsoft SQL Server"))
        self.dialectCB.setItemText(4, _translate("Dialog", "SQLite"))
        self.label_1.setText(_translate("Dialog", "Dialect:"))
        self.label_2.setText(_translate("Dialog", "Username:"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.label_4.setText(_translate("Dialog", "Host:Port:"))
        self.label_5.setText(_translate("Dialog", "Database:"))
        self.label_6.setText(_translate("Dialog", "Table:"))
